# Oracle Settings
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=c##user
spring.datasource.password=1234



# Mapper
mybatis.mapper-locations= mapper/*.xml

resource.path=file:///C:/Users/kyj/Desktop/upload/
upload.path=/upload/**

#JSP
spring.mvc.view.prefix=/WEB-INF/view
spring.mvc.view.suffix=.jsp

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB